import React from 'react';

function About() {
  return (
    <div className="Page">
      <div className="PageHeader">
        <div className="PageHeader__Contents">
          <h1>The year is 3369 and, throughout the universe, all biological life has been decimated. All that's left are Prime Bots that Humans sent to explore space. It's up to the Prime Bots to buidl their own future. They'll need help from the Worker and Support Bots in order to survive.</h1>
        </div>
      </div>
      <div className="Block Columns Contain">
        <div className="Columns__Column--33">
          <h2>Bots are NFTs</h2>
          <p>All Bots are unique ERC-721 Non-fungible Tokens.</p>
        </div>
        <div className="Columns__Column--33">
          <h2>Bot DNA is based on Code.</h2>
          <p>When a bot is generated, your codebase is used to generate it's DNA.</p>
        </div>
        <div className="Columns__Column--33">
          <h2>Support Open Source</h2>
          <p>Donate to any open source project on Gittron and get a Support Bot NFT.</p>
        </div>
      </div>
      <div className="Block">
        <div className="Block__Contents">
          <h2>Prime Bots</h2>
          <p>Managers of a open-source repo can generate a unique Prime Bot. The DNA of your Prime Bot is based on your repo's codebase.            
          </p>
        </div>
      </div>
      <div className="Block">
        <div className="Block__Contents">
          <h2>Buidl Bots</h2>
          <p>Buidl Bots are special rare clones of the Prime Bot that can be generated by the owner and distributed to contributors on their repo.            
          </p>
        </div>
      </div>
      <div className="Block">
        <div className="Block__Contents">
          <h2>Support Bots</h2>
          <p>Supporters of the open source project can generate a clone of a Prime Bot, known as a Support Bot. The DNA of the Support Bot is a direct clone of the Prime Bot, including any rare elements, but upon generation will also receive some unique traits such as colors.         
          </p>
        </div>
      </div>
    </div>
  );
}

export default About;
