import React from 'react';

function About() {
  return (
    <div className="Page">
      <div className="PageHeader">
        <div className="PageHeader__Contents">
          <h1>The year is 3369 and, throughout the universe, all biological life has been decimated. All that's left are Prime Bots that Humans sent to explore space. It's up to the Prime Bots to buidl their own future. They'll need help from the Worker and Support Bots in order to survive.</h1>
        </div>
      </div>
      <div className="Block Columns Contain">
        <div className="Columns__Column--33">
          <h2>Support Open Source</h2>
          <p>Donate to any open source project on Gittron and get a Support Bot NFT.</p>
        </div>
        <div className="Columns__Column--33">
          <h2>Bots are NFTs</h2>
          <p>All Bots are unique ERC-721 Non-fungible Tokens.</p>
        </div>
        <div className="Columns__Column--33">
          <h2>Bot DNA is based on Code.</h2>
          <p>When a bot is generated, your codebase is used to generate it's DNA.</p>
        </div>
      </div>
      <div className="Block Black">
        <div className="Block__Contents Contain">
          <h2>Prime Bots</h2>
          <p>Managers of an open-source repo can generate a unique Prime Bot. The DNA of the Prime Bot is based on the repo's codebase.            
          </p>
          <p>With a Prime Bot generated, it can be cloned as Buidl Bots and Support Bots.</p>
        </div>
      </div>
      <div className="Block Border-Bottom">
        <div className="Block__Contents Contain">
          <h2>Buidl Bots</h2>
          <p>Buidl Bots are special rare clones of the Prime Bot that can be generated by the owner and distributed to contributors on their repo for free.            
          </p>
        </div>
      </div>
      <div className="Block Border-Bottom">
        <div className="Block__Contents Contain">
          <h2>Support Bots</h2>
          <p>Supporters of an open source project can clone a Prime Bot as a Support Bot. The DNA of the Support Bot is a direct clone of the Prime Bot, including any rare elements, but upon generation will also receive some unique traits such as colors.
          </p>
        </div>
      </div>
      <div className="Block">
        <div className="Block__Contents Contain">
          <h2>FAQs</h2>
          <p><strong>What's the Contract Address?</strong></p>
          <p>0x95a86872332732bc124f0c5606c8a10bf9d50e50</p>
          <p><strong>How do I generate a Prime Bot?</strong></p>
          <p>Authenticate with Web3 Wallet and go to Dashboard. In Dashboard, you can register a new repo. Set a price for how much you want to accept per Support Bot and a Wallet Address to receive the funds from supports.</p>
          <p><strong>How do I get a Buidl Bot?</strong></p>
          <p>The owner of a Prime Bot can gift you a Buidl Bot if they haven't used thm all.</p>
          <p><strong>Who built this silly thing?</strong></p>
          <p>Odyssy is a decentralized collective sending design and development to blockchain and beyond. Connect with us at <a href="https://odyssy.io" target="_blank" rel="noopener noreferrer">odyssy.io</a></p>
        </div>
      </div>
    </div>
  );
}

export default About;
